### ISSUE TITLE
Meteostation

### ISSUE THREAD

**Issue by cmdoret** [Hackuarium/beemos#4]
Slave ATMEGA328

Slave I2C:

- https://github.com/lpatiny/legoino/tree/master/eagle/halloween/halloween2013/led-driver

LDR: Spectro board for pot

 - https://github.com/opatiny/stea-mp-unk-3/tree/master/eagle/cardReader
 - pin analogique

One wire:

 - 18B20
 - https://www.diymodules.org/eagle-show-object?type=usr&id=2575&device=DS18B20

DHT22

Pressure:

 - https://www.mouser.ch/datasheet/2/418/NG_DS_MS5637-02BA03_B1-1130139.pdf
 - on 2 pins to make software wire (I2C) (not SCL and SDA)
 - or pressure sensor that use another protocol

**Comment by lpatiny** [comment]
Done
