### ISSUE TITLE
move all the slaves in slaves-i2c

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/beemos#8]
@cmdoret you could also rename it to slave maybe

**Comment by cmdoret** [comment]
Done, there is also a "master" board and a "mainboard". Not sure about the distinction between  the two. I think one should be removed.

**Comment by lpatiny** [comment]
Yes I think there could be a 'master' folder containing 2 projects. @oliemery you could create one more level 'master' and migrate your code inside this new folder (as well as the 'master-simple' that could be renamed 'simple'

**Comment by lpatiny** [comment]
We will probably still refactor the project ...
